version: '3.4'

services:
  detection:
    image: detection:local
    build:
      context: detection
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
  recognition:
    image: recognition:local
    build:
      context: recognition
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
  http-api:
    image:  http-api:local
    build:
      context:  http-api
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000             