apiVersion: v1
kind: Service
metadata:
    name: "daprtalkdemo-3f17"
    labels:
        app: "daprtalkdemo-3f17"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "daprtalkdemo-3f17"