apiVersion: v1
kind: Service
metadata:
    name: "daprtalkdemo-38ab"
    labels:
        app: "daprtalkdemo-38ab"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "daprtalkdemo-38ab"