apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - detection.yaml
  - http-api.yaml
  - recognition.yaml
  - ingress.yaml
  - dapr.yaml
  
images:
  - name: detection
    newTag: local
  - name: recognition
    newTag: local
  - name: http-api
    newTag: local

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: Never
