apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - detection.yaml
  - http-api.yaml
  - recognition.yaml
  - ingress.yaml
  - dapr.yaml
  
# images:
#   - name: detection
#     newTag: local
#   - name: recognition
#     newTag: local
#   - name: http-api
#     newTag: local

# patches:
#   - target:
#       kind: Deployment
#     patch: |-
#       - op: add
#         path: "/spec/template/spec/containers/0/imagePullPolicy"
#         value: Never

images:
  - name: detection
    newName: daprtalk.azurecr.io/detection
    newTag: f1849fef809947a1eb3e275b43678d1030d66a43
  - name: recognition
    newName: daprtalk.azurecr.io/recognition
    newTag: f1849fef809947a1eb3e275b43678d1030d66a43
  - name: http-api
    newName: daprtalk.azurecr.io/http-api
    newTag: f1849fef809947a1eb3e275b43678d1030d66a43

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: IfNotPresent