apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1  
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
# ---
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: pubsub
#   namespace: default
# spec:
#   type: pubsub.azure.servicebus
#   version: v1
#   metadata:
#   - name: connectionString # Required
#     value: ""